app:
  datasource:
    main:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3307/SICOPTEST
      username: user1
      password: 'user123'
      pool-size: 30

server:
  error:
    include-binding-errors: always
    include-message: always


